### ISSUE TITLE
Support cascading OnInput events and OnInput events on all relevant elements

### ISSUE THREAD

**Issue by kkoreilly** [cogentcore/core#750]

**Comment by kkoreilly** [comment]
This has been implemented in the commits above.

**Comment by ddkwork** [comment]
> 这已在上面的提交中实现。

The oninput event feels like a bug, the input text is not displayed, and the event responds correctly
![screenshots](https://github.com/cogentcore/core/assets/19886504/5e26390d-33f6-48bd-b708-37acda44aa0d)

**Comment by ddkwork** [comment]
please reopen

**Comment by kkoreilly** [comment]
I will work on fixing this soon.

**Comment by kkoreilly** [comment]
The `OnInput` event seems to work normally for me; can you try running the latest version of the demo, going to `Dialogs`, then `Full window` under `Dialogs`, and then typing things into the struct view and watching the `Got input event` log messages?

**Comment by ddkwork** [comment]
> The `OnInput` event seems to work normally for me; can you try running the latest version of the demo, going to `Dialogs`, then `Full window` under `Dialogs`, and then typing things into the struct view and watching the `Got input event` log messages?

I've just figured out the confusion: it seems a bit of a problem to refresh the struct widget inside the input event, and I'll make a demo to illustrate it later

**Comment by ddkwork** [comment]
> The event seems to work normally for me; can you try running the latest version of the demo, going to , then under , and then typing things into the struct view and watching the log messages?`OnInput``Dialogs``Full window``Dialogs``Got input event`

```go
package main

import (
	"cogentcore.org/core/events"
	"cogentcore.org/core/gi"
	"cogentcore.org/core/giv"
	"fmt"
)

func main() {
	b := gi.NewBody("xx")
	type HashData struct {
		Src    string `width:"150"`
		Md2    string `width:"150"`
		Md4    string `width:"150"`
		Md5    string `width:"150"`
		Sha1   string `width:"150"`
		Sha224 string `width:"150"`
		Sha256 string `width:"150"`
		Sha384 string `width:"150"`
		Sha512 string `width:"150"`
	}
	hashData := &HashData{
		Src:    "",
		Md2:    "",
		Md4:    "",
		Md5:    "",
		Sha1:   "",
		Sha224: "",
		Sha256: "",
		Sha384: "",
		Sha512: "",
	}
	hashStructView := giv.NewStructView(b).SetStruct(hashData)
	hashStructView.OnInput(func(e events.Event) {
		async := hashStructView.UpdateStart()
		*hashData = HashData{
			Src:    hashData.Src,
			Md2:    "11 " + hashData.Src,
			Md4:    "22 " + hashData.Src,
			Md5:    "33 " + hashData.Src,
			Sha1:   "44 " + hashData.Src,
			Sha224: "55 " + hashData.Src,
			Sha256: "66 " + hashData.Src,
			Sha384: "77 " + hashData.Src,
			Sha512: "88 " + hashData.Src,
		}
		fmt.Printf("%#v\n", hashData)
		hashStructView.UpdateFields()
		hashStructView.UpdateEndRender(async)
	})
	b.RunMainWindow()
}

```

**Comment by kkoreilly** [comment]
When you are in an event handler, like `OnInput`, that is **not** asynchronous, as it is part of the main event loop. However, updating it directly doesn't work because it resets the text field, so I need to think about this a little bit more first. I will get back to you later today.

**Comment by kkoreilly** [comment]
Also, you no longer need to add `max-width:"0"` to all of the fields, since I fixed it so that it automatically makes the max at least as big as the min.

**Comment by kkoreilly** [comment]
I fixed the updating issue, and this code should work now:

```go
        hashStructView.OnInput(func(e events.Event) {
		updt := hashStructView.UpdateStart()
		*hashData = HashData{
			Src:    hashData.Src, //After entering data in this field, the following fields are not refreshed to the UI
			Md2:    "11",         //Theoretically, it is possible to re-instantiate a HashData struct and SetStruct(hashData), but then we can't take the input information
			Md4:    "22",
			Md5:    "33",
			Sha1:   "44",
			Sha224: "55",
			Sha256: "66",
			Sha384: "77",
			Sha512: "88",
		}
		hashStructView.UpdateFields()
		hashStructView.UpdateEndRender(updt)
	})
```

**Comment by ddkwork** [comment]
> I fixed the updating issue, and this code should work now:
> 
> ```go
>         hashStructView.OnInput(func(e events.Event) {
> 		updt := hashStructView.UpdateStart()
> 		*hashData = HashData{
> 			Src:    hashData.Src, //After entering data in this field, the following fields are not refreshed to the UI
> 			Md2:    "11",         //Theoretically, it is possible to re-instantiate a HashData struct and SetStruct(hashData), but then we can't take the input information
> 			Md4:    "22",
> 			Md5:    "33",
> 			Sha1:   "44",
> 			Sha224: "55",
> 			Sha256: "66",
> 			Sha384: "77",
> 			Sha512: "88",
> 		}
> 		hashStructView.UpdateFields()
> 		hashStructView.UpdateEndRender(updt)
> 	})
> ```

Testing found that there were also some issues: the trace log found that the entered information was not stored. I updated the demo code

![{715FA54D-10C7-4ffc-8611-D25650A45B3B}](https://github.com/cogentcore/core/assets/19886504/a0a22306-11c5-4f6b-aa9a-9c346d73a610)

**Comment by ddkwork** [comment]
Another way is to add a button to perform the click event, but does it only refresh the NewStructView or only the pointer?
Since the last demo found SetStruct, setslice, and other features that can't be set twice, I'm very sensitive to these APIs, maybe we can maintain a set xxx number of times inside the widget, so that the runtime or compiler finds the wrong behavior,
If a non-asynchronous quadratic Set works, then for the sake of simplicity, I guess I should add a button to change the layout code and response logic

**Comment by ddkwork** [comment]
However, I found that even if we add a button to respond, we still have to get the input information, so this should be a problem that must be solved

**Comment by ddkwork** [comment]
Previously, the only way to effectively take user input and populate it into a pointer variable was to press the keyboard's enter key.

**Comment by kkoreilly** [comment]
I will add a struct tag that supports this behavior.

**Comment by kkoreilly** [comment]
I implemented this in the commit above; if you add an `immediate:"+"` struct tag to the `Src` field, changes to it will be immediately applied to the struct on input. You should only need to call `SetStruct` and `NewStructView` once.

**Comment by ddkwork** [comment]
> I implemented this in the commit above; if you add an `immediate:"+"` struct tag to the `Src` field, changes to it will be immediately applied to the struct on input. You should only need to call `SetStruct` and `NewStructView` once.

It still didn't work as expected, and I don't think it's easy to describe this kind of trouble in the demo for the changes in the rest of the fields, so I'm going to access a minimal demo of a real-world scene to illustrate. However, my poor English still can't guarantee that it will be clearly described, so if you can, come to my machine.

**Comment by kkoreilly** [comment]
You are correct that I don't seem to understand the issue, so a simple demo would be helpful. Otherwise, I can look into it when I debug on your machine, which I will probably do tomorrow.

**Comment by ddkwork** [comment]
> You are correct that I don't seem to understand the issue, so a simple demo would be helpful. Otherwise, I can look into it when I debug on your machine, which I will probably do tomorrow.

![screenshots](https://github.com/cogentcore/core/assets/19886504/8cab5451-335c-47d8-9f70-0b470af3336c)

**Comment by kkoreilly** [comment]
Did you add the `immediate:"+"` struct tag? Are you sure that the issue is with the struct updating, not your encryption logic?

**Comment by ddkwork** [comment]
> immediate:"+"

 I'm so sorry I forgot that, now it works as expected, perfect fix, thank you

**Comment by ddkwork** [comment]
> Did you add the `immediate:"+"` struct tag? Are you sure that the issue is with the struct updating, not your encryption logic?

As an aside, you don't have to think about it: immediate is too long for someone like me who has only learned a little bit of English to remember, and the Infinite feature I am sure will be used frequently in subsequent project portings, so I can add == immediate || == imm, so I don't have to copy and paste immediate every time, hehe. However, for the code, I still insist on spelling the signature and struct field of the interface, so that I don't need to look at the doc, and I don't have to spell it all, because goland will index it, and the interesting thing is that the scene is all familiar words, such as index, item, etc., and you can understand its function at a glance when calling them. Thanks again for the fix, it will feel like the ease of use of the core is much stronger, for me.

**Comment by kkoreilly** [comment]
We do not want to have something unclear and abbreviated like `imm` in a struct tag, but if you have an idea for a simpler word we could do instead of immediate that describes the behavior, I am willing to do that.

**Comment by ddkwork** [comment]
> We do not want to have something unclear and abbreviated like `imm` in a struct tag, but if you have an idea for a simpler word we could do instead of immediate that describes the behavior, I am willing to do that.

That's it, leave it alone, it's already very easy to use, and compared to the previous hassle of pressing enter once for each edit box widget, this fix is perfect.
